pub const Instructions = enum(u16) {
    NOP,
    CLEAR,
    MOV, // move within registers
    ADD_I,
    ADD_F,
    SUB_I,
    SUB_F,
    MUL_I,
    MUL_F,
    DIV_I,
    DIV_F,
    MOD_I,
    MOD_F,
    POW_I,
    POW_F,
    BOOL_AND,
    BOOL_OR,
    BOOL_NOT,
    BIN_XOR,
    BIN_AND,
    BIN_OR,
    BIN_NOT,
    BIN_SHIFTL,
    BIN_SHIFTR,
    BIN_ROLLL,
    BIN_ROLLR,
    INC,
    DEC,
    LD8,
    LD16,
    LD32,
    LD64,
    STO8,
    STO16,
    STO32,
    STO64,
    LD_CONST,
    PUSH,
    PUSH_ALL, // includes all registers like accum (mostly for preserving state)
    POP,
    POP_ALL,
    CMP_EQ,
    CMP_NEQ,
    CMP_LT,
    CMP_LE,
    CMP_GT,
    CMP_GE,
    BRANCH_LABEL,
    BRANCH,
    BRANCH_TRUE_LABEL,
    BRANCH_TRUE,
    BRANCH_FALSE_LABEL,
    BRANCH_FALSE,
    LABEL,
    CALL_DIRECT,
    CALL_INDIRECT,
    CALL_TRUE_DIRECT, // via constant identifier
    CALL_TRUE_INDIRECT, // via function pointer
    CALL_FALSE_DIRECT,
    CALL_FALSE_INDIRECT,
    RET,
    RET_TRUE,
    RET_FALSE,
    ITOF,
    FTOI,
    WIDEN_F, // force an f32 into an f64. This is for when we load an f32 and want to widen it for math operations. This is required for math operations to be valid
    TRIM_F, // force f64 value into 32bit size. THIS IS ONLY USED FOR WRITING AN F32 to memory and subsequent math operations will be invalid
};
